project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /Pal.Client/Properties/*.resx
    ignore:
      - /Pal.Client/Properties/Localization.*.resx
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
