//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pal.Client.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pal.Client.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please chose one of the options above..
        /// </summary>
        internal static string Agreement_PickOneOption {
            get {
                return ResourceManager.GetString("Agreement_PickOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand I&apos;m using this plugin on my own risk..
        /// </summary>
        internal static string Agreement_UsingThisOnMyOwnRisk {
            get {
                return ResourceManager.GetString("Agreement_UsingThisOnMyOwnRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View plugin &amp; server source code.
        /// </summary>
        internal static string Agreement_ViewPluginAndServerSourceCode {
            get {
                return ResourceManager.GetString("Agreement_ViewPluginAndServerSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While this is not an automation feature, you&apos;re still very likely to break the ToS..
        /// </summary>
        internal static string Agreement_Warning1 {
            get {
                return ResourceManager.GetString("Agreement_Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other players in your party can always see where you&apos;re standing/walking..
        /// </summary>
        internal static string Agreement_Warning2 {
            get {
                return ResourceManager.GetString("Agreement_Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As such, please avoid mentioning it in-game and do not share videos/screenshots..
        /// </summary>
        internal static string Agreement_Warning3 {
            get {
                return ResourceManager.GetString("Agreement_Warning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the configuration window.
        /// </summary>
        internal static string Command_pal_HelpText {
            get {
                return ResourceManager.GetString("Command_pal_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view statistics for the floor you&apos;re currently on by opening the &apos;Debug&apos; tab in the configuration window..
        /// </summary>
        internal static string Command_pal_stats_CurrentFloor {
            get {
                return ResourceManager.GetString("Command_pal_stats_CurrentFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch statistics..
        /// </summary>
        internal static string Command_pal_stats_UnableToFetchStatistics {
            get {
                return ResourceManager.GetString("Command_pal_stats_UnableToFetchStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown sub-command &apos;{0}&apos; for &apos;{1}&apos;..
        /// </summary>
        internal static string Command_pal_UnknownSubcommand {
            get {
                return ResourceManager.GetString("Command_pal_UnknownSubcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are NOT in a deep dungeon..
        /// </summary>
        internal static string Config_Debug_NotInADeepDungeon {
            get {
                return ResourceManager.GetString("Config_Debug_NotInADeepDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as:.
        /// </summary>
        internal static string Config_Export_SaveAs {
            get {
                return ResourceManager.GetString("Config_Export_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all markers from {0}:.
        /// </summary>
        internal static string Config_ExportSource {
            get {
                return ResourceManager.GetString("Config_ExportSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Coffer color.
        /// </summary>
        internal static string Config_GoldCoffer_Color {
            get {
                return ResourceManager.GetString("Config_GoldCoffer_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw filled.
        /// </summary>
        internal static string Config_GoldCoffer_Filled {
            get {
                return ResourceManager.GetString("Config_GoldCoffer_Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Gold Treasure Coffer Locations.
        /// </summary>
        internal static string Config_GoldCoffer_Show {
            get {
                return ResourceManager.GetString("Config_GoldCoffer_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows nearby gold coffers (containing pomanders) on the current floor.
        ///This is not synchronized with other players and not saved between floors/runs..
        /// </summary>
        internal static string Config_GoldCoffers_ToolTip {
            get {
                return ResourceManager.GetString("Config_GoldCoffers_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoard Coffer color.
        /// </summary>
        internal static string Config_HoardCoffers_Color {
            get {
                return ResourceManager.GetString("Config_HoardCoffers_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide hoard coffers not on current floor.
        /// </summary>
        internal static string Config_HoardCoffers_HideImpossible {
            get {
                return ResourceManager.GetString("Config_HoardCoffers_HideImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a Pomander of intuition, only the actual hoard coffer location is visible, all other (potential) hoard coffers are hidden..
        /// </summary>
        internal static string Config_HoardCoffers_HideImpossible_ToolTip {
            get {
                return ResourceManager.GetString("Config_HoardCoffers_HideImpossible_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hoard coffers.
        /// </summary>
        internal static string Config_HoardCoffers_Show {
            get {
                return ResourceManager.GetString("Config_HoardCoffers_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit GitHub.
        /// </summary>
        internal static string Config_Import_VisitGitHub {
            get {
                return ResourceManager.GetString("Config_Import_VisitGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports are available from {0} (as *.pal files)..
        /// </summary>
        internal static string Config_ImportDownloadLocation {
            get {
                return ResourceManager.GetString("Config_ImportDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using an export is useful if you&apos;re unable to connect to the server, or don&apos;t wish to share your findings..
        /// </summary>
        internal static string Config_ImportExplanation1 {
            get {
                return ResourceManager.GetString("Config_ImportExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports are (currently) generated manually, and they only include traps and hoard coffers encountered by 5 or more people. This may lead to higher floors having very sporadic coverage, but commonly run floors (e.g. PotD 51-60, HoH 21-30) are closer to complete..
        /// </summary>
        internal static string Config_ImportExplanation2 {
            get {
                return ResourceManager.GetString("Config_ImportExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you aren&apos;t offline, importing a file won&apos;t have any noticeable effect..
        /// </summary>
        internal static string Config_ImportExplanation3 {
            get {
                return ResourceManager.GetString("Config_ImportExplanation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never upload discoveries, show only traps and coffers I found myself.
        /// </summary>
        internal static string Config_NeverUploadDiscoveries_ShowMyTraps {
            get {
                return ResourceManager.GetString("Config_NeverUploadDiscoveries_ShowMyTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string Config_Renderer_Simple {
            get {
                return ResourceManager.GetString("Config_Renderer_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experimental.
        /// </summary>
        internal static string Config_Renderer_Simple_Hint {
            get {
                return ResourceManager.GetString("Config_Renderer_Simple_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splatoon.
        /// </summary>
        internal static string Config_Renderer_Splatoon {
            get {
                return ResourceManager.GetString("Config_Renderer_Splatoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default, required Splatoon to be installed.
        /// </summary>
        internal static string Config_Renderer_Splatoon_Hint {
            get {
                return ResourceManager.GetString("Config_Renderer_Splatoon_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to Import:.
        /// </summary>
        internal static string Config_SelectImportFile {
            get {
                return ResourceManager.GetString("Config_SelectImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to *.pal file.
        /// </summary>
        internal static string Config_SelectImportFile_Hint {
            get {
                return ResourceManager.GetString("Config_SelectImportFile_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which render backend to use for markers:.
        /// </summary>
        internal static string Config_SelectRenderBackend {
            get {
                return ResourceManager.GetString("Config_SelectRenderBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Coffer color.
        /// </summary>
        internal static string Config_SilverCoffer_Color {
            get {
                return ResourceManager.GetString("Config_SilverCoffer_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw filled.
        /// </summary>
        internal static string Config_SilverCoffer_Filled {
            get {
                return ResourceManager.GetString("Config_SilverCoffer_Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Silver Treasure Coffer Locations.
        /// </summary>
        internal static string Config_SilverCoffer_Show {
            get {
                return ResourceManager.GetString("Config_SilverCoffer_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows nearby silver coffers (gear upgrades and magicites) on the current floor.
        ///This is not synchronized with other players and not saved between floors/runs..
        /// </summary>
        internal static string Config_SilverCoffers_ToolTip {
            get {
                return ResourceManager.GetString("Config_SilverCoffers_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw trap &amp; coffer circles around self.
        /// </summary>
        internal static string Config_Splatoon_DrawCircles {
            get {
                return ResourceManager.GetString("Config_Splatoon_DrawCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Export.
        /// </summary>
        internal static string Config_StartExport {
            get {
                return ResourceManager.GetString("Config_StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Import.
        /// </summary>
        internal static string Config_StartImport {
            get {
                return ResourceManager.GetString("Config_StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string Config_TestConnection {
            get {
                return ResourceManager.GetString("Config_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        internal static string Config_TestConnection_Connecting {
            get {
                return ResourceManager.GetString("Config_TestConnection_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap color.
        /// </summary>
        internal static string Config_Traps_Color {
            get {
                return ResourceManager.GetString("Config_Traps_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide traps not on current floor.
        /// </summary>
        internal static string Config_Traps_HideImpossible {
            get {
                return ResourceManager.GetString("Config_Traps_HideImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a Pomander of Sight, only the actual trap locations are visible, all other traps are hidden.
        ///When using a Pomander of Safety, all traps are hidden..
        /// </summary>
        internal static string Config_Traps_HideImpossible_ToolTip {
            get {
                return ResourceManager.GetString("Config_Traps_HideImpossible_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show traps.
        /// </summary>
        internal static string Config_Traps_Show {
            get {
                return ResourceManager.GetString("Config_Traps_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Import.
        /// </summary>
        internal static string Config_UndoImport {
            get {
                return ResourceManager.GetString("Config_UndoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last import was on {0}, which added the trap/hoard coffer database from {1} created on {2:d}..
        /// </summary>
        internal static string Config_UndoImportExplanation1 {
            get {
                return ResourceManager.GetString("Config_UndoImportExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think that was a mistake, you can remove all locations only found in the import (any location you&apos;ve seen yourself is not changed)..
        /// </summary>
        internal static string Config_UndoImportExplanation2 {
            get {
                return ResourceManager.GetString("Config_UndoImportExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload my discoveries, show traps &amp; coffers other players have discovered.
        /// </summary>
        internal static string Config_UploadMyDiscoveries_ShowOtherTraps {
            get {
                return ResourceManager.GetString("Config_UploadMyDiscoveries_ShowOtherTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string ConfigTab_Community {
            get {
                return ResourceManager.GetString("ConfigTab_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string ConfigTab_Debug {
            get {
                return ResourceManager.GetString("ConfigTab_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dungeons.
        /// </summary>
        internal static string ConfigTab_DeepDungeons {
            get {
                return ResourceManager.GetString("ConfigTab_DeepDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ConfigTab_Export {
            get {
                return ResourceManager.GetString("ConfigTab_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ConfigTab_Import {
            get {
                return ResourceManager.GetString("ConfigTab_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer.
        /// </summary>
        internal static string ConfigTab_Renderer {
            get {
                return ResourceManager.GetString("ConfigTab_Renderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server: {0}.
        /// </summary>
        internal static string ConnectionError_CouldNotConnectToServer {
            get {
                return ResourceManager.GetString("ConnectionError_CouldNotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create account ({0})..
        /// </summary>
        internal static string ConnectionError_CreateAccountFailed {
            get {
                return ResourceManager.GetString("ConnectionError_CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account-id after account was attempted to be created..
        /// </summary>
        internal static string ConnectionError_CreateAccountReturnedNoId {
            get {
                return ResourceManager.GetString("ConnectionError_CreateAccountReturnedNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account id..
        /// </summary>
        internal static string ConnectionError_InvalidAccountId {
            get {
                return ResourceManager.GetString("ConnectionError_InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log in ({0})..
        /// </summary>
        internal static string ConnectionError_LoginFailed {
            get {
                return ResourceManager.GetString("ConnectionError_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No login information available..
        /// </summary>
        internal static string ConnectionError_LoginReturnedNoToken {
            get {
                return ResourceManager.GetString("ConnectionError_LoginReturnedNoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not online..
        /// </summary>
        internal static string ConnectionError_NotOnline {
            get {
                return ResourceManager.GetString("ConnectionError_NotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Palace Pal is outdated, please update the plugin using the Plugin Installer..
        /// </summary>
        internal static string ConnectionError_OldVersion {
            get {
                return ResourceManager.GetString("ConnectionError_OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        internal static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command could not be executed: {0}.
        /// </summary>
        internal static string Error_CommandFailed {
            get {
                return ResourceManager.GetString("Error_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please finish the initial setup first..
        /// </summary>
        internal static string Error_FirstTimeSetupRequired {
            get {
                return ResourceManager.GetString("Error_FirstTimeSetupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        internal static string Error_ImportFailed {
            get {
                return ResourceManager.GetString("Error_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: Incompatible version..
        /// </summary>
        internal static string Error_ImportFailed_IncompatibleVersion {
            get {
                return ResourceManager.GetString("Error_ImportFailed_IncompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: Invalid file..
        /// </summary>
        internal static string Error_ImportFailed_InvalidFile {
            get {
                return ResourceManager.GetString("Error_ImportFailed_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin could not be loaded: {0}.
        /// </summary>
        internal static string Error_LoadFailed {
            get {
                return ResourceManager.GetString("Error_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install this plugin from the official repository at {0} to continue using it..
        /// </summary>
        internal static string Error_WrongRepository {
            get {
                return ResourceManager.GetString("Error_WrongRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eureka Orthos.
        /// </summary>
        internal static string EurekaOrthos {
            get {
                return ResourceManager.GetString("EurekaOrthos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pal Palace will show where potential trap &amp; hoard coffer locations are..
        /// </summary>
        internal static string Explanation_1 {
            get {
                return ResourceManager.GetString("Explanation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To do this, using a pomander to reveal trap or treasure chest locations will save the position of what you see..
        /// </summary>
        internal static string Explanation_2 {
            get {
                return ResourceManager.GetString("Explanation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideally, we want to discover every potential trap and chest location in the game, but doing this alone is very tedious. Floor 51-60 has over 300 trap locations and over 290 coffer locations - and we don&apos;t know if that map is complete. Higher floors naturally see fewer runs, making solo attempts to map the place much harder..
        /// </summary>
        internal static string Explanation_3 {
            get {
                return ResourceManager.GetString("Explanation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can decide whether you want to share traps and chests you find with the community, which likewise also will let you see chests and coffers found by other players. This can be changed at any time. No data regarding your FFXIV character or account is ever sent to our server..
        /// </summary>
        internal static string Explanation_4 {
            get {
                return ResourceManager.GetString("Explanation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heaven on High.
        /// </summary>
        internal static string HeavenOnHigh {
            get {
                return ResourceManager.GetString("HeavenOnHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} new trap locations and {1} new hoard coffer locations..
        /// </summary>
        internal static string ImportCompleteStatistics {
            get {
                return ResourceManager.GetString("ImportCompleteStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palace Pal.
        /// </summary>
        internal static string Palace_Pal {
            get {
                return ResourceManager.GetString("Palace_Pal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palace of the Dead.
        /// </summary>
        internal static string PalaceOfTheDead {
            get {
                return ResourceManager.GetString("PalaceOfTheDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accursed Hoard.
        /// </summary>
        internal static string pnAccursed_Hoard {
            get {
                return ResourceManager.GetString("pnAccursed Hoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accursed Hoard Outline Colour.
        /// </summary>
        internal static string pnAccursed_Hoard_Outline_Colour {
            get {
                return ResourceManager.GetString("pnAccursed Hoard Outline Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Coffer color.
        /// </summary>
        internal static string pnBronze_Coffer_color {
            get {
                return ResourceManager.GetString("pnBronze Coffer color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffers.
        /// </summary>
        internal static string pnCoffers {
            get {
                return ResourceManager.GetString("pnCoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common settings.
        /// </summary>
        internal static string pnCommon_settings {
            get {
                return ResourceManager.GetString("pnCommon settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Bronze Treasure Coffer Locations.
        /// </summary>
        internal static string pnDisplay_Bronze_Treasure_Coffer_Locations {
            get {
                return ResourceManager.GetString("pnDisplay Bronze Treasure Coffer Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Passages.
        /// </summary>
        internal static string pnDisplay_Passages {
            get {
                return ResourceManager.GetString("pnDisplay Passages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Potential Accursed Hoard Coffer Locations.
        /// </summary>
        internal static string pnDisplay_Potential_Accursed_Hoard_Coffer_Locations {
            get {
                return ResourceManager.GetString("pnDisplay Potential Accursed Hoard Coffer Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the location of anywhere an Accursed Hoard coffer has been found..
        /// </summary>
        internal static string pnDisplay_Potential_Accursed_Hoard_Coffer_Locations_Help {
            get {
                return ResourceManager.GetString("pnDisplay Potential Accursed Hoard Coffer Locations Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Potential Trap Locations.
        /// </summary>
        internal static string pnDisplay_Potential_Trap_Locations {
            get {
                return ResourceManager.GetString("pnDisplay Potential Trap Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the potential location of invisible floor traps.
        /// </summary>
        internal static string pnDisplay_Potential_Trap_Locations_Help {
            get {
                return ResourceManager.GetString("pnDisplay Potential Trap Locations Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Traps Filled.
        /// </summary>
        internal static string pnDraw_Traps_Filled {
            get {
                return ResourceManager.GetString("pnDraw Traps Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Outline Colour.
        /// </summary>
        internal static string pnExit_Outline_Colour {
            get {
                return ResourceManager.GetString("pnExit Outline Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Accursed Hoard Locations on Intuition Use.
        /// </summary>
        internal static string pnHide_Accursed_Hoard_Locations_on_Intuition_Use {
            get {
                return ResourceManager.GetString("pnHide Accursed Hoard Locations on Intuition Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable rendering of potential Accursed Hoard coffer locations when using a Pommander of Intuition until the Accursed Hoard is found..
        /// </summary>
        internal static string pnHide_Accursed_Hoard_Locations_on_Intuition_Use_Help {
            get {
                return ResourceManager.GetString("pnHide Accursed Hoard Locations on Intuition Use Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Traps on Safety/Sight Use.
        /// </summary>
        internal static string pnHide_Traps_on_Safety_Sight_Use {
            get {
                return ResourceManager.GetString("pnHide Traps on Safety/Sight Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable rendering of potential traps that are not actually present on this floor after revealing/banishing them via Sight or Safety pomanders..
        /// </summary>
        internal static string pnHide_Traps_on_Safety_Sight_Use_Help {
            get {
                return ResourceManager.GetString("pnHide Traps on Safety/Sight Use Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight When Activated.
        /// </summary>
        internal static string pnHighlight_When_Activated {
            get {
                return ResourceManager.GetString("pnHighlight When Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default the Passage will be marked only with a yellow outline and text label, enabling this will also enable a bright green fill..
        /// </summary>
        internal static string pnHighlight_When_Activated_Help {
            get {
                return ResourceManager.GetString("pnHighlight When Activated Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Mimic Trap Coffer color.
        /// </summary>
        internal static string pnMimic_Coffer_color {
            get {
                return ResourceManager.GetString("pnMimic Coffer color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only mimics in bronze chests on early floor sets can be detected..
        /// </summary>
        internal static string pnMimic_Help {
            get {
                return ResourceManager.GetString("pnMimic Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passages.
        /// </summary>
        internal static string pnPassages {
            get {
                return ResourceManager.GetString("pnPassages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text overlay.
        /// </summary>
        internal static string pnText_overlay {
            get {
                return ResourceManager.GetString("pnText overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text overlay font scale.
        /// </summary>
        internal static string pnText_overlay_font_scale {
            get {
                return ResourceManager.GetString("pnText overlay font scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap Outline Colour.
        /// </summary>
        internal static string pnTrap_Outline_Colour {
            get {
                return ResourceManager.GetString("pnTrap Outline Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps.
        /// </summary>
        internal static string pnTraps {
            get {
                return ResourceManager.GetString("pnTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoard.
        /// </summary>
        internal static string Statistics_HoardCoffers {
            get {
                return ResourceManager.GetString("Statistics_HoardCoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        internal static string Statistics_InstanceName {
            get {
                return ResourceManager.GetString("Statistics_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Statistics_TerritoryId {
            get {
                return ResourceManager.GetString("Statistics_TerritoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps.
        /// </summary>
        internal static string Statistics_Traps {
            get {
                return ResourceManager.GetString("Statistics_Traps", resourceCulture);
            }
        }
    }
}
