// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Pal.Client.Database.Compiled
{
    [DbContext(typeof(PalClientContext))]
    public partial class PalClientContextModel : RuntimeModel
    {
        static PalClientContextModel()
        {
            var model = new PalClientContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PalClientContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
